### ISSUE TITLE
lcpkg not working anymore

### ISSUE THREAD

**Issue by TheSystemIsCorrupt** [lc-soft/LCUI#255]
Hi there, It seems lcpkg dependenices are deprecated and it's not working anymore.
I use this command to build lcui but it fails with the following error...

1. I run cmd
2. I cd in to the lcui source repo root
3. I run `lcpkg install --arch x64`

Here is error : 
```
C:\Users\SystemIsCorrupt\Desktop\LCUI-2.2.0>lcpkg install
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:167:9)
    at LCPkg.resolvePackage (C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\src\index.js:106:25)
    at C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\src\index.js:135:49
    at Array.map (<anonymous>)
    at LCPkg.loadPackages (C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\src\index.js:135:30)
    at run (C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\src\cli-install.js:180:24)
    at Command.<anonymous> (C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\src\cli-install.js:230:5)
    at Command.listener [as _actionHandler] (C:\Users\SystemIsCorrupt\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:426:31) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
am I doing something wrong? or is it from the lcpkg?

regards,
Marius

**Comment by lc-soft** [comment]
Have you installed vcpkg and added its path to lcpkg's configuration?

**Comment by TheSystemIsCorrupt** [comment]
@lc-soft I just put vcpkg in c:\ and now it works! thanks for the hint!
is there anyway to get the source of `libxml2-lite` ?

**Comment by lc-soft** [comment]
> @lc-soft I just put vcpkg in c:\ and now it works! thanks for the hint!
> is there anyway to get the source of `libxml2-lite` ?
> I want to build them using MT

Source:

https://github.com/lc-soft/LCUI/tree/develop/lcpkg/ports/libxml2-lite

It is modified from vcpkg/ports/libxml2:

https://github.com/microsoft/vcpkg/tree/master/ports/libxml2
